### ISSUE TITLE
Mobile view

### ISSUE THREAD

**Issue by Svish** [bennettdams/eslintconfig.dev#1]
Not the best 🤔

![Screenshot_20200830-235719](https://user-images.githubusercontent.com/142162/91670320-9c2c9300-eb1c-11ea-8423-802a711cdc07.png)

**Comment by bennettdams** [comment]
Added a naive mobile implementation via https://github.com/bennettdams/eslintconfig.dev/commit/6383f7b4003c551924845a860c2e6053c05849a5

![image](https://user-images.githubusercontent.com/29319414/91671496-853f6e00-eb27-11ea-8222-b35cc6851361.png)
