### ISSUE TITLE
dependency version ranges

### ISSUE THREAD

**Issue by mpvosseller** [bennettdams/eslintconfig.dev#8]
Is there a reason that all the dependencies have a version range except `eslint-config-react-app`?

I guess I would have expected the version ranges to have been omitted unless there was some known issue. Is there a known issue (or constraint of some kind) on the versions that we should be aware of when we upgrade later?

```
npm install --save-dev eslint-config-react-app @typescript-eslint/eslint-plugin@^4.0.0 @typescript-eslint/parser@^4.0.0 babel-eslint@^10.0.0 eslint@^7.5.0 eslint-plugin-flowtype@^5.2.0 eslint-plugin-import@^2.22.0 eslint-plugin-jsx-a11y@^6.3.1 eslint-plugin-react@^7.20.3 eslint-plugin-react-hooks@^4.0.8 prettier@^2.1.2 eslint-config-prettier@^6.12.0 eslint-plugin-prettier@^3.1.4
```

**Comment by bennettdams** [comment]
There was no thought in omitting the version, I agree that it makes sense to use a fixed version for `eslint-config-react-app`. Maybe we should also show two different "Create React App" templates on the site, one for "<v4" and one for ">=v4" of CRA.
